# Generated by Django 3.1.8 on 2021-04-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('external_id', models.CharField(max_length=20, unique=True, verbose_name='IMDb ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('external_id', models.CharField(max_length=20, unique=True, verbose_name='IMDb ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('score', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Score')),
                ('synopsis', models.TextField(verbose_name='Synopsis')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('duration', models.TimeField(verbose_name='Duration')),
                ('cover', models.URLField(verbose_name='Cover')),
                ('actors', models.ManyToManyField(related_name='_movie_actors_+', to='movies.Person', verbose_name='Actors')),
                ('directors', models.ManyToManyField(related_name='_movie_directors_+', to='movies.Person', verbose_name='Directors')),
                ('genres', models.ManyToManyField(to='movies.Genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
