# Generated by Django 3.1.8 on 2021-05-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Import Movie',
                'verbose_name_plural': 'Import Movie',
            },
        ),
    ]
