# Generated by Django 3.1.8 on 2021-05-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_importmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='movies.Person', verbose_name='Actors'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='movies_directed', to='movies.Person', verbose_name='Directors'),
        ),
    ]
